#!/usr/bin/env python3
"""
gemini_web_automator.py

Option B: Gemini 3.1 Pro Web UI Automator via Playwright (Chrome CDP)

What this script does:
1. Connects to your running Chrome instance on `http://127.0.0.1:9223` (where you are logged into Gemini).
2. Opens `https://gemini.google.com/app` in a new tab.
3. Automatically pastes the weekly prompt (`prompts_for_gemini/<Course>/<Week>_prompt.md`).
4. Submits the prompt to Gemini 3.1 Pro and intelligently waits for the full response to finish generating.
5. Saves the output note straight into your Obsidian Vault (`OBSIDIAN_VAULT_DIR`).
6. Uses Playwright headless HTML->PDF rendering to export a beautifully styled `.pdf` alongside the `.md` note.


Usage:
    # Run for a specific course & week:
    python gemini_web_automator.py --course "May 2026 - BDM" --week "Week 1"

    # Or run across all weeks sequentially:
    python gemini_web_automator.py
"""

import argparse
import asyncio
import os
import sys
import time
from dotenv import load_dotenv
from playwright.async_api import async_playwright

load_dotenv()

OBSIDIAN_VAULT_DIR = os.environ.get("OBSIDIAN_VAULT_DIR", os.path.join(os.getcwd(), "Obsidian_Vault"))
PROMPTS_DIR = "prompts_for_gemini"

# Try importing markdown for HTML -> PDF styling
try:
    import markdown
except ImportError:
    markdown = None


def get_html_template(title: str, markdown_content: str) -> str:
    if markdown:
        try:
            body_html = markdown.markdown(
                markdown_content,
                extensions=["tables", "fenced_code", "nl2br", "sane_lists"]
            )
        except Exception:
            body_html = f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{markdown_content}</pre>"
    else:
        body_html = f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{markdown_content}</pre>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <script>
        window.MathJax = {{
            tex: {{
                inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
                displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],
                processEscapes: true
            }},
            svg: {{
                fontCache: 'global'
            }}
        }};
    </script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
    <style>
        @page {{ size: A4; margin: 20mm 15mm 20mm 15mm; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1a1a1a; margin: 0; padding: 0; font-size: 11pt; }}
        h1, h2, h3, h4 {{ color: #111827; font-weight: 700; margin-top: 1.5em; margin-bottom: 0.5em; page-break-after: avoid; }}
        h1 {{ font-size: 20pt; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.3em; }}
        h2 {{ font-size: 15pt; border-bottom: 1px solid #f3f4f6; padding-bottom: 0.2em; }}
        h3 {{ font-size: 12.5pt; }}
        p, ul, ol {{ margin-bottom: 1em; }}
        code {{ font-family: Consolas, monospace; background-color: #f3f4f6; padding: 0.2em 0.4em; border-radius: 4px; font-size: 0.9em; color: #dc2626; }}
        pre {{ background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 12px; overflow-x: auto; page-break-inside: avoid; }}
        pre code {{ background-color: transparent; padding: 0; color: #334155; }}
        table {{ width: 100%; border-collapse: collapse; margin: 1.5em 0; page-break-inside: avoid; }}
        th, td {{ border: 1px solid #cbd5e1; padding: 10px 12px; text-align: left; }}
        th {{ background-color: #f1f5f9; font-weight: 600; }}
        tr:nth-child(even) {{ background-color: #f8fafc; }}
        blockquote {{ border-left: 4px solid #3b82f6; margin: 1em 0; padding: 1em; color: #475569; background-color: #eff6ff; }}
        .header-meta {{ font-size: 0.9em; color: #64748b; margin-bottom: 2em; border-bottom: 1px solid #e2e8f0; padding-bottom: 1em; }}
        mjx-container {{ display: inline-block; margin: 0.2em 0; }}
        mjx-container[display="true"] {{ display: block; margin: 1em 0; text-align: center; }}
    </style>
</head>
<body>
    <div class="header-meta">
        <strong>Course:</strong> {title.split(' - ')[0] if ' - ' in title else title} &nbsp;|&nbsp; 
        <strong>Generated by:</strong> Gemini 3.1 Pro (Web UI) &nbsp;|&nbsp; 
        <strong>Study Notes & Exam Review</strong>
    </div>
    {body_html}
</body>
</html>"""


async def convert_html_to_pdf(html_content: str, pdf_output_path: str):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.set_content(html_content, wait_until="networkidle")
        # Ensure MathJax finishes rendering SVG equations before printing PDF
        try:
            await page.evaluate("() => window.MathJax && window.MathJax.typesetPromise && window.MathJax.typesetPromise()")
            await page.wait_for_timeout(2000)
        except Exception:
            pass
        await page.pdf(path=pdf_output_path, format="A4", print_background=True, margin={"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"})
        await browser.close()


def get_system_clipboard_text() -> str:
    """Reads text directly from Windows system clipboard so we can get clean Markdown copied by Gemini's Copy button without browser focus issues."""
    try:
        import tkinter as tk
        root = tk.Tk()
        root.withdraw()
        text = root.clipboard_get()
        root.destroy()
        return text
    except Exception:
        pass
    try:
        import subprocess
        output = subprocess.check_output(["powershell", "-NoProfile", "-Command", "Get-Clipboard -Raw"], text=True, encoding="utf-8")
        return output
    except Exception:
        return ""


async def generate_note_in_gemini_web(page, prompt_text: str, course_name: str, week_name: str) -> str:
    print(f"  [Web UI] Navigating to https://gemini.google.com/app ...")
    await page.goto("https://gemini.google.com/app", wait_until="domcontentloaded")
    await page.wait_for_timeout(4000)

    # Locate the chat input box (rich-textarea / contenteditable / textarea)
    print("  [Web UI] Locating prompt input area...")
    input_selector = "rich-textarea, div[contenteditable='true'], textarea"
    await page.wait_for_selector(input_selector, timeout=15000)
    
    # Focus and set prompt text natively so rich-textarea doesn't freeze or ignore input
    input_elem = page.locator(input_selector).first
    await input_elem.click()
    await page.wait_for_timeout(500)

    print(f"  [Web UI] Inserting {len(prompt_text)} characters of prompt text natively...")
    # Use document.execCommand('insertText') which natively triggers all input/change events without breaking Angular/Lit
    inserted = await page.evaluate("""(text) => {
        const el = document.querySelector("rich-textarea, div[contenteditable='true'], textarea");
        if (el) {
            el.focus();
            document.execCommand('insertText', false, text);
            return true;
        }
        return false;
    }""", prompt_text)

    if not inserted:
        # Fallback using clipboard paste
        await page.evaluate("(text) => navigator.clipboard.writeText(text)", prompt_text)
        await page.keyboard.press("Control+v")
    
    await page.wait_for_timeout(2000)

    # Robust submission loop: keep clicking Send / pressing Control+Enter until prompt box clears and generation starts
    print("  [Web UI] Submitting prompt...")
    for send_attempt in range(1, 6):
        send_button = page.locator("button[aria-label*='Send'], button[aria-label*='send'], button.send-button, button[mattooltip*='Send']").first
        if await send_button.count() > 0 and await send_button.is_visible():
            await send_button.click(force=True)
        else:
            await page.keyboard.press("Control+Enter")
        
        await page.wait_for_timeout(3000)

        # Check if generation started by seeing if stop button appeared or if input box cleared
        stop_btn = page.locator("button[aria-label*='Stop'], button:has-text('Stop generating')")
        if await stop_btn.count() > 0 and await stop_btn.is_visible():
            print("  [Web UI] Generation verified running!")
            break
            
        # Check if text cleared from rich-textarea
        input_text = await input_elem.inner_text() if await input_elem.count() > 0 else ""
        if len(input_text.strip()) < 50:
            print("  [Web UI] Prompt cleared from input box; generation starting...")
            break
            
        print(f"  [Web UI] Re-triggering Send (attempt {send_attempt}/5)...")
    
    # Poll until generation stops (e.g., stop generating button disappears or response stabilizes)
    max_wait_seconds = 180
    start_poll = time.time()
    last_length = 0
    stable_count = 0

    while time.time() - start_poll < max_wait_seconds:
        # Check if "Continue generating" or similar button appeared
        continue_btn = page.locator("button:has-text('Continue'), button:has-text('continue generating')").first
        if await continue_btn.count() > 0 and await continue_btn.is_visible():
            print("  [Web UI] Clicking 'Continue generating' button...")
            await continue_btn.click()
            await page.wait_for_timeout(3000)

        # Get all response containers (model messages)
        response_elems = page.locator(".model-response-text, message-content, .markdown, .response-container-content")
        count = await response_elems.count()
        if count > 0:
            latest_text = await response_elems.nth(count - 1).inner_text()
            current_length = len(latest_text)
            
            # Check if text length has stabilized (has stopped growing for ~8 seconds)
            if current_length > 500 and current_length == last_length:
                stable_count += 1
                if stable_count >= 4:  # ~8 seconds of stability
                    print(f"  [Web UI] Generation completed (~{current_length} characters). Extracting pristine Markdown...")
                    # 1. First choice: Click the official 'Copy' button on Gemini's response so math equations & LaTeX are copied perfectly intact!
                    try:
                        copy_buttons = page.locator("button[aria-label*='Copy'], button[mattooltip*='Copy'], button[data-test-id*='copy']")
                        if await copy_buttons.count() > 0:
                            await copy_buttons.last.click()
                            await page.wait_for_timeout(1500)
                            # First check system clipboard directly using Python (works even when browser window is unfocused!)
                            sys_clip = get_system_clipboard_text()
                            if sys_clip and len(sys_clip) > 300:
                                print("  [Web UI] Successfully extracted clean Markdown via Gemini Copy button (system clipboard)!")
                                return sys_clip
                            # Fallback check browser clipboard via JS
                            clipboard_text = await page.evaluate("() => navigator.clipboard.readText().catch(() => '')")
                            if clipboard_text and len(clipboard_text) > 300:
                                print("  [Web UI] Successfully extracted clean Markdown via Gemini Copy button (browser clipboard)!")
                                return clipboard_text
                    except Exception as e:
                        print(f"  [Copy Button Notice] Could not read clipboard ({e}); falling back to DOM extraction...")

                    # 2. Second choice: Extract from DOM while cleanly reconstructing Math equations from KaTeX annotations
                    return await response_elems.nth(count - 1).evaluate("""el => {
                        const clone = el.cloneNode(true);
                        clone.querySelectorAll('.katex').forEach(span => {
                            const annotation = span.querySelector('annotation[encoding="application/x-tex"]');
                            if (annotation && annotation.textContent) {
                                span.textContent = '$' + annotation.textContent.trim() + '$';
                            }
                        });
                        return clone.innerText || clone.textContent;
                    }""")
            else:
                last_length = current_length
                stable_count = 0
                print(f"  [Generating...] Current output length: {current_length} characters...")
        
        await page.wait_for_timeout(2000)

    # Fallback return of whatever generated so far if timeout hit
    response_elems = page.locator(".model-response-text, message-content, .markdown, .response-container-content")
    if await response_elems.count() > 0:
        try:
            copy_buttons = page.locator("button[aria-label*='Copy'], button[mattooltip*='Copy']")
            if await copy_buttons.count() > 0:
                await copy_buttons.last.click()
                await page.wait_for_timeout(1500)
                sys_clip = get_system_clipboard_text()
                if sys_clip and len(sys_clip) > 100:
                    return sys_clip
                clipboard_text = await page.evaluate("() => navigator.clipboard.readText().catch(() => '')")
                if clipboard_text and len(clipboard_text) > 100:
                    return clipboard_text
        except Exception:
            pass
        return await response_elems.last.evaluate("""el => {
            const clone = el.cloneNode(true);
            clone.querySelectorAll('.katex').forEach(span => {
                const annotation = span.querySelector('annotation[encoding="application/x-tex"]');
                if (annotation && annotation.textContent) {
                    span.textContent = '$' + annotation.textContent.trim() + '$';
                }
            });
            return clone.innerText || clone.textContent;
        }""")
    
    raise RuntimeError("Timed out waiting for Gemini response in Web UI.")


async def process_prompt_file(context, prompt_file_path: str, course_name: str, week_name: str):
    print("\n" + "=" * 80)
    print(f"PROCESSING VIA GEMINI WEB UI (3.1 PRO): {course_name} | {week_name}")
    print("=" * 80)

    safe_course = "".join(c for c in course_name if c.isalnum() or c in (" ", "-", "_")).strip()
    safe_week = "".join(c for c in week_name if c.isalnum() or c in (" ", "-", "_")).strip()
    course_vault_dir = os.path.join(OBSIDIAN_VAULT_DIR, safe_course)
    obsidian_md_path = os.path.join(course_vault_dir, f"{safe_week}_Notes.md")
    
    if os.path.exists(obsidian_md_path):
        print(f"  [Skipping] Note already exists at `{obsidian_md_path}`")
        return

    with open(prompt_file_path, "r", encoding="utf-8") as pf:
        prompt_text = pf.read()

    page = await context.new_page()
    try:
        await context.grant_permissions(["clipboard-read", "clipboard-write"], origin="https://gemini.google.com")
    except Exception:
        pass
    try:
        notes_markdown = await generate_note_in_gemini_web(page, prompt_text, course_name, week_name)
    except Exception as e:
        print(f"  [Failed] Could not generate notes via Web UI for {course_name} - {week_name}: {e}")
        await page.close()
        return
    finally:
        await page.close()

    if not notes_markdown or len(notes_markdown) < 100:
        print("  [Warning] Extracted notes appear very short or empty.")
        return

    # Save to Obsidian Vault
    safe_course = "".join(c for c in course_name if c.isalnum() or c in (" ", "-", "_")).strip()
    safe_week = "".join(c for c in week_name if c.isalnum() or c in (" ", "-", "_")).strip()

    course_vault_dir = os.path.join(OBSIDIAN_VAULT_DIR, safe_course)
    os.makedirs(course_vault_dir, exist_ok=True)

    obsidian_md_path = os.path.join(course_vault_dir, f"{safe_week}_Notes.md")
    
    full_md_note = f"# {course_name} - {week_name} Study Notes\n\n"
    full_md_note += f"> **Generated by:** Gemini 3.1 Pro (Web UI)\n> **Course:** {course_name}\n> **Week:** {week_name}\n\n---\n\n"
    full_md_note += notes_markdown

    with open(obsidian_md_path, "w", encoding="utf-8") as out_md:
        out_md.write(full_md_note)
    print(f"  [Obsidian Note Saved] -> `{obsidian_md_path}`")

    # Export to PDF
    pdf_output_path = os.path.join(course_vault_dir, f"{safe_week}_Notes.pdf")
    html_content = get_html_template(f"{course_name} - {week_name}", notes_markdown)
    
    try:
        print("  [PDF Export] Rendering clean PDF from Markdown note...")
        print("  [PDF Export] SKIPPED (as requested)...")
        # await convert_html_to_pdf(html_content, pdf_output_path)
        print(f"  [PDF Saved] -> `{pdf_output_path}`")
    except Exception as e:
        print(f"  [PDF Warning] Could not export PDF: {e}")


async def main():
    parser = argparse.ArgumentParser(description="Gemini 3.1 Pro Web UI Automator")
    parser.add_argument("--course", help="Filter by specific course name (e.g. 'May 2026 - BDM')")
    parser.add_argument("--week", help="Filter by specific week name (e.g. 'Week 1')")
    parser.add_argument("--port", type=int, default=9223, help="Remote debugging port for Chrome (default: 9223)")
    args = parser.parse_args()

    if not os.path.exists(PROMPTS_DIR):
        print(f"[Error] Prompts directory `{PROMPTS_DIR}` not found.")
        sys.exit(1)

    prompt_files = []
    for root, _, files in os.walk(PROMPTS_DIR):
        for file in files:
            if file.endswith("_prompt.md") and file != "all_week_prompts_consolidated.md":
                course_folder = os.path.basename(root)
                week_str = file.replace("_prompt.md", "")

                if args.course and args.course.lower() not in course_folder.lower():
                    continue
                if args.week and args.week.lower() != week_str.lower():
                    continue

                prompt_files.append((os.path.join(root, file), course_folder, week_str))

    if not prompt_files:
        print("[Warning] No prompt files matched your filter.")
        return

    cdp_url = f"http://127.0.0.1:{args.port}"
    print(f"Attaching to Chrome CDP session on {cdp_url} ...")
    async with async_playwright() as p:
        try:
            browser = await p.chromium.connect_over_cdp(cdp_url)
        except Exception as e:
            print(f"[Connection Error] Could not attach to Chrome on port {args.port}: {e}")
            print(f"Make sure Chrome is running with `--remote-debugging-port={args.port}` and logged into gemini.google.com!")
            return

        contexts = browser.contexts
        if not contexts:
            print("[Error] No browser context found!")
            return
        context = contexts[0]

        print(f"\nFound {len(prompt_files)} prompt(s) to process via Gemini 3.1 Pro Web UI.")
        for pf_path, course_name, week_name in prompt_files:
            await process_prompt_file(context, pf_path, course_name, week_name)

    print("\n" + "=" * 80)
    print("ALL WEB UI AUTOMATION & PDF EXPORTS COMPLETED!")
    print(f"Check your Obsidian Vault: `{OBSIDIAN_VAULT_DIR}`")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
