#!/usr/bin/env python3
"""
generate_and_export_notes.py

Automated AI Study Notes Generator & PDF Exporter (Option A - Direct API Pipeline)

What this script does:
1. Reads weekly prompts generated by `generate_notes_prompts.py` (`prompts_for_gemini/<Course>/<Week>_prompt.md`).
2. Calls the Gemini API (`google-genai` SDK) using your `GEMINI_API_KEY` to generate exhaustive, self-contained exam notes.
3. Automatically saves the response as a clean Markdown note (`.md`) inside your Obsidian Vault.
4. Uses Playwright headless Chrome to convert that Markdown note into a beautifully styled, professional PDF (`.pdf`) right next to the Markdown file.
5. Handles rate limits automatically (`time.sleep` + exponential backoff retries) so you never hit quota errors.

Usage:
    # Generate notes & PDF for all courses and weeks:
    python generate_and_export_notes.py

    # Or generate for a specific course/week (faster):
    python generate_and_export_notes.py --course "May 2026 - MLT" --week "Week 1"
"""

import argparse
import asyncio
import os
import sys
import time
from pathlib import Path
from dotenv import load_dotenv

# Try importing official Google GenAI SDK
try:
    from google import genai
    from google.genai import errors as genai_errors
except ImportError:
    print("[Error] `google-genai` library not found. Please install via `pip install google-genai`.")
    sys.exit(1)

# Try importing Playwright for PDF export
try:
    from playwright.async_api import async_playwright
except ImportError:
    print("[Error] `playwright` library not found. Please install via `pip install playwright`.")
    sys.exit(1)

# Try importing markdown for HTML conversion
try:
    import markdown
except ImportError:
    # Fallback or simple converter if markdown package isn't present
    markdown = None

# Load environment variables
load_dotenv()

# Configuration
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
OBSIDIAN_VAULT_DIR = os.environ.get("OBSIDIAN_VAULT_DIR", os.path.join(os.getcwd(), "Obsidian_Vault"))
PROMPTS_DIR = "prompts_for_gemini"

# Default Model: you can change to "gemini-3.1-pro" or "gemini-1.5-pro" or "gemini-1.5-flash"
MODEL_NAME = "gemini-1.5-pro"

# Delay between API requests to stay strictly under the free tier rate limit (2 requests per minute for Pro models)
RATE_LIMIT_DELAY_SECONDS = 35


def get_html_template(title: str, markdown_content: str) -> str:
    """
    Converts Markdown into a beautifully styled, professional HTML page
    with typography matching Obsidian / modern academic notes suitable for PDF rendering.
    """
    if markdown:
        # Convert using Python markdown with tables & fenced_code extensions if available
        try:
            body_html = markdown.markdown(
                markdown_content,
                extensions=["tables", "fenced_code", "nl2br", "sane_lists"]
            )
        except Exception:
            body_html = f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{markdown_content}</pre>"
    else:
        body_html = f"<pre style='white-space: pre-wrap; font-family: sans-serif;'>{markdown_content}</pre>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <script>
        window.MathJax = {{
            tex: {{
                inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
                displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],
                processEscapes: true
            }},
            svg: {{
                fontCache: 'global'
            }}
        }};
    </script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
    <style>
        @page {{
            size: A4;
            margin: 20mm 15mm 20mm 15mm;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #1a1a1a;
            margin: 0;
            padding: 0;
            font-size: 11pt;
        }}
        h1, h2, h3, h4 {{
            color: #111827;
            font-weight: 700;
            margin-top: 1.5em;
            margin-bottom: 0.5em;
            page-break-after: avoid;
        }}
        h1 {{
            font-size: 20pt;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 0.3em;
        }}
        h2 {{
            font-size: 15pt;
            border-bottom: 1px solid #f3f4f6;
            padding-bottom: 0.2em;
        }}
        h3 {{
            font-size: 12.5pt;
        }}
        p, ul, ol {{
            margin-bottom: 1em;
        }}
        li {{
            margin-bottom: 0.3em;
        }}
        code {{
            font-family: Consolas, Monaco, "Andale Mono", monospace;
            background-color: #f3f4f6;
            padding: 0.2em 0.4em;
            border-radius: 4px;
            font-size: 0.9em;
            color: #dc2626;
        }}
        pre {{
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 12px;
            overflow-x: auto;
            page-break-inside: avoid;
        }}
        pre code {{
            background-color: transparent;
            padding: 0;
            color: #334155;
            font-size: 0.85em;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.5em 0;
            page-break-inside: avoid;
        }}
        th, td {{
            border: 1px solid #cbd5e1;
            padding: 10px 12px;
            text-align: left;
        }}
        th {{
            background-color: #f1f5f9;
            font-weight: 600;
        }}
        tr:nth-child(even) {{
            background-color: #f8fafc;
        }}
        blockquote {{
            border-left: 4px solid #3b82f6;
            margin: 1em 0;
            padding-left: 1em;
            color: #475569;
            background-color: #eff6ff;
            padding-top: 0.5em;
            padding-bottom: 0.5em;
            border-radius: 0 4px 4px 0;
        }}
        .header-meta {{
            font-size: 0.9em;
            color: #64748b;
            margin-bottom: 2em;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 1em;
        }}
        mjx-container {{ display: inline-block; margin: 0.2em 0; }}
        mjx-container[display="true"] {{ display: block; margin: 1em 0; text-align: center; }}
    </style>
</head>
<body>
    <div class="header-meta">
        <strong>Course:</strong> {title.split(' - ')[0] if ' - ' in title else title} &nbsp;|&nbsp; 
        <strong>Generated by:</strong> Gemini API ({MODEL_NAME}) &nbsp;|&nbsp; 
        <strong>Study Notes & Exam Review</strong>
    </div>
    {body_html}
</body>
</html>"""


async def convert_html_to_pdf(html_content: str, pdf_output_path: str):
    """Uses Playwright headless browser to render HTML and save as a high-quality PDF."""
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.set_content(html_content, wait_until="networkidle")
        try:
            await page.evaluate("() => window.MathJax && window.MathJax.typesetPromise && window.MathJax.typesetPromise()")
            await page.wait_for_timeout(2000)
        except Exception:
            pass
        await page.pdf(
            path=pdf_output_path,
            format="A4",
            print_background=True,
            margin={"top": "20mm", "bottom": "20mm", "left": "15mm", "right": "15mm"}
        )
        await browser.close()


def generate_notes_with_retry(client: genai.Client, prompt_text: str, max_retries: int = 4) -> str:
    """Calls Gemini API with exponential backoff on quota / rate limit errors."""
    for attempt in range(1, max_retries + 1):
        try:
            print(f"  [API Call] Sending prompt to {MODEL_NAME}...")
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=prompt_text
            )
            if not response or not response.text:
                raise ValueError("Received empty response from Gemini API.")
            return response.text
        except Exception as e:
            err_str = str(e).lower()
            if "429" in err_str or "quota" in err_str or "rate limit" in err_str or "exhausted" in err_str:
                wait_sec = 25 * (2 ** (attempt - 1))
                print(f"  [Rate Limit Caught] 429 / Quota limit reached. Waiting {wait_sec}s before retry {attempt}/{max_retries}...")
                time.sleep(wait_sec)
            else:
                if attempt == max_retries:
                    raise
                print(f"  [API Error] {e}. Retrying in 10 seconds ({attempt}/{max_retries})...")
                time.sleep(10)
    raise RuntimeError("Failed to generate notes after maximum retries.")


async def process_prompt_file(client: genai.Client, prompt_file_path: str, course_name: str, week_name: str):
    """Processes a single prompt file: generates notes via Gemini, saves to Obsidian, exports to PDF."""
    print("\n" + "=" * 80)
    print(f"PROCESSING: {course_name} | {week_name}")
    print("=" * 80)

    with open(prompt_file_path, "r", encoding="utf-8") as pf:
        prompt_text = pf.read()

    # 1. Generate Notes via Gemini API
    start_time = time.time()
    try:
        notes_markdown = generate_notes_with_retry(client, prompt_text)
    except Exception as e:
        print(f"  [Failed] Could not generate notes for {course_name} - {week_name}: {e}")
        return
    elapsed = round(time.time() - start_time, 1)
    print(f"  [Success] Generated {len(notes_markdown)} characters of detailed notes in {elapsed}s!")

    # 2. Prepare Obsidian Vault Directory
    safe_course = "".join(c for c in course_name if c.isalnum() or c in (" ", "-", "_")).strip()
    safe_week = "".join(c for c in week_name if c.isalnum() or c in (" ", "-", "_")).strip()

    course_vault_dir = os.path.join(OBSIDIAN_VAULT_DIR, safe_course)
    os.makedirs(course_vault_dir, exist_ok=True)

    obsidian_md_path = os.path.join(course_vault_dir, f"{safe_week}_Notes.md")
    
    # Add title and metadata block to markdown note
    full_md_note = f"# {course_name} - {week_name} Study Notes\n\n"
    full_md_note += f"> **Generated by:** Gemini ({MODEL_NAME})\n> **Course:** {course_name}\n> **Week:** {week_name}\n\n---\n\n"
    full_md_note += notes_markdown

    with open(obsidian_md_path, "w", encoding="utf-8") as out_md:
        out_md.write(full_md_note)
    print(f"  [Obsidian Note Saved] -> `{obsidian_md_path}`")

    # 3. Export to PDF via Playwright
    pdf_output_path = os.path.join(course_vault_dir, f"{safe_week}_Notes.pdf")
    html_content = get_html_template(f"{course_name} - {week_name}", notes_markdown)
    
    try:
        print("  [PDF Export] Converting Markdown note to beautifully styled PDF...")
        await convert_html_to_pdf(html_content, pdf_output_path)
        print(f"  [PDF Saved] -> `{pdf_output_path}`")
    except Exception as e:
        print(f"  [PDF Warning] Could not export PDF: {e}")


async def main():
    parser = argparse.ArgumentParser(description="Automated AI Notes & PDF Exporter via Gemini API")
    parser.add_argument("--course", help="Filter by specific course name (e.g. 'May 2026 - MLT')")
    parser.add_argument("--week", help="Filter by specific week name (e.g. 'Week 1')")
    args = parser.parse_args()

    if not GEMINI_API_KEY:
        print("[Error] GEMINI_API_KEY is not set in `.env`.")
        sys.exit(1)

    print(f"Initializing Gemini Client with model: `{MODEL_NAME}`")
    client = genai.Client(api_key=GEMINI_API_KEY)

    if not os.path.exists(PROMPTS_DIR):
        print(f"[Error] Prompts directory `{PROMPTS_DIR}` not found. Please run `generate_notes_prompts.py` first.")
        sys.exit(1)

    # Collect matching prompt files
    prompt_files_to_process = []
    for root, _, files in os.walk(PROMPTS_DIR):
        for file in files:
            if file.endswith("_prompt.md") and file != "all_week_prompts_consolidated.md":
                # Folder structure: prompts_for_gemini/<Course>/<Week>_prompt.md
                course_folder = os.path.basename(root)
                week_str = file.replace("_prompt.md", "")

                if args.course and args.course.lower() not in course_folder.lower():
                    continue
                if args.week and args.week.lower() != week_str.lower():
                    continue

                full_path = os.path.join(root, file)
                prompt_files_to_process.append((full_path, course_folder, week_str))

    # Sort logically by course and week
    def sort_key(item):
        _, c_name, w_name = item
        num = "".join([ch for ch in w_name if ch.isdigit()])
        return (c_name, int(num) if num else 99)

    prompt_files_to_process.sort(key=sort_key)

    if not prompt_files_to_process:
        print("[Warning] No prompt files found matching your criteria.")
        return

    print(f"\nFound {len(prompt_files_to_process)} weekly prompts to process.")
    print(f"Obsidian Vault directory set to: `{OBSIDIAN_VAULT_DIR}`\n")

    for idx, (pf_path, course_name, week_name) in enumerate(prompt_files_to_process, start=1):
        await process_prompt_file(client, pf_path, course_name, week_name)

        # Apply rate limiting delay if there are more files remaining
        if idx < len(prompt_files_to_process):
            print(f"\n  [Rate Limit Pause] Sleeping for {RATE_LIMIT_DELAY_SECONDS}s before next request to respect Gemini API free tier limits...")
            time.sleep(RATE_LIMIT_DELAY_SECONDS)

    print("\n" + "=" * 80)
    print("ALL STUDY NOTES & PDF EXPORTS COMPLETED SUCCESSFULLY!")
    print(f"Check your Obsidian Vault: `{OBSIDIAN_VAULT_DIR}`")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
